"""Tests for the AGP tag pre-run checks of pretext-to-asm and pretext-to-asm-recurate."""

from pathlib import Path
from unittest.mock import patch

import pytest
import rich_click as click

from grit.steps.post_curation.pretext_to_asm import _OUTPUT_SPECS, _run_pretext_to_asm_core
from grit.steps.post_curation.pretext_to_asm_recurate import _check_unloc_tags
from grit.utils.helpers import iter_agp_rows, parse_agp_tags

# Standard 9-column AGP row; PretextView appends its tags from column 10 on.
# Column 1 is PretextView's own object name, column 6 the component carried
# over from the assembly — that's where a previous round's unloc name lives.
_ROW = "{name}\t1\t1000\t1\tW\t{component}\t1\t1000\t+"


def _agp(path: Path, lines: list[str]) -> Path:
    header = [
        "##agp-version\t2.1",
        "# DESCRIPTION: Generated by PretextViewAI Version 1.0.6",
    ]
    path.write_text("\n".join(header + lines) + "\n")
    return path


def _core(ctx, tmp_path, agp_lines):
    """Run _run_pretext_to_asm_core against an on-disk AGP with a mocked pretext-to-asm."""
    ctx.workdir = tmp_path
    ctx.tracker = None
    (tmp_path / "original.fa").write_text(">seq\nACGT\n")
    _agp(tmp_path / f"{ctx.tol_id}.curated.agp", agp_lines)
    with patch("grit.steps.post_curation.pretext_to_asm._run") as mock_run:
        _run_pretext_to_asm_core(
            ctx,
            "pretext_to_asm",
            tmp_path / "original.fa",
            "missing original.fa",
            tmp_path,
            f"{ctx.tol_id}.fa",
            _OUTPUT_SPECS,
        )
    return mock_run


def test_parse_agp_tags_reads_extra_columns(tmp_path):
    agp = _agp(
        tmp_path / "x.agp",
        [
            _ROW.format(name="SUPER_1", component="SCAFFOLD_1") + "\tCut\tHAP1",
            _ROW.format(name="SUPER_2", component="SCAFFOLD_2"),
        ],
    )
    assert parse_agp_tags(agp) == {"SUPER_1": {"cut", "hap1"}, "SUPER_2": set()}


def test_parse_agp_tags_on_missing_file_is_empty(tmp_path):
    assert parse_agp_tags(tmp_path / "nope.agp") == {}


def test_primary_tag_present_passes(mock_ctx_primary, tmp_path):
    mock_ctx_primary.combine_for_curation = True
    mock_run = _core(
        mock_ctx_primary,
        tmp_path,
        [_ROW.format(name="SUPER_1", component="SCAFFOLD_1") + "\tPrimary"],
    )
    mock_run.assert_called_once()


def test_primary_tag_missing_fails_before_running(mock_ctx_primary, tmp_path):
    mock_ctx_primary.combine_for_curation = True
    with pytest.raises(click.ClickException) as exc:
        _core(
            mock_ctx_primary,
            tmp_path,
            [_ROW.format(name="SUPER_1", component="SCAFFOLD_1") + "\tHAP1"],
        )
    assert "primary" in str(exc.value).lower()
    assert "PretextView" in str(exc.value)


def test_primary_tag_not_required_without_combine_for_curation(mock_ctx_primary, tmp_path):
    """A single-hap assembly curated in its own window needs no primary tag."""
    assert mock_ctx_primary.combine_for_curation is False
    mock_run = _core(
        mock_ctx_primary, tmp_path, [_ROW.format(name="SUPER_1", component="SCAFFOLD_1")]
    )
    mock_run.assert_called_once()


def test_primary_tag_not_required_for_dual_hap_ticket(mock_ctx, tmp_path):
    """hap1/hap2 tickets are tagged per haplotype, not 'primary'."""
    assert mock_ctx.combine_for_curation is True
    mock_run = _core(
        mock_ctx, tmp_path, [_ROW.format(name="SUPER_1", component="SCAFFOLD_1") + "\tHAP1"]
    )
    mock_run.assert_called_once()


def test_unloc_check_passes_when_tag_reapplied(tmp_path):
    agp = _agp(
        tmp_path / "recurate.agp",
        [
            _ROW.format(name="Scaffold_1", component="SUPER_1_HAP1"),
            _ROW.format(name="Scaffold_1", component="SUPER_1_unloc_1_HAP1") + "\tPainted\tUnloc",
        ],
    )
    _check_unloc_tags(agp)


def test_unloc_check_fails_listing_untagged_components(tmp_path):
    agp = _agp(
        tmp_path / "recurate.agp",
        [
            _ROW.format(name="Scaffold_1", component="SUPER_1_HAP1"),
            _ROW.format(name="Scaffold_1", component="SUPER_1_unloc_1_HAP1"),
            _ROW.format(name="Scaffold_2", component="SUPER_2_unloc_3_HAP1") + "\tPainted",
            _ROW.format(name="Scaffold_3", component="SUPER_3_unloc_1_HAP1") + "\tUnloc",
        ],
    )
    with pytest.raises(click.ClickException) as exc:
        _check_unloc_tags(agp)
    message = str(exc.value)
    assert "SUPER_1_unloc_1_HAP1" in message
    assert "SUPER_2_unloc_3_HAP1" in message
    assert "SUPER_3_unloc_1_HAP1" not in message


def test_unloc_check_ignores_freshly_made_unlocs(tmp_path):
    """An unloc created in this round is tagged but its component keeps the raw scaffold name."""
    agp = _agp(
        tmp_path / "recurate.agp",
        [_ROW.format(name="Scaffold_1", component="HAP1_SCAFFOLD_681") + "\tPainted\tUnloc"],
    )
    _check_unloc_tags(agp)


@patch("grit.steps.post_curation.pretext_to_asm._run")
@patch("grit.steps.post_curation.pretext_to_asm_recurate.find_canonical_fa")
def test_recurate_step_applies_the_unloc_check(mock_find_fa, mock_run, mock_ctx, tmp_path):
    from grit.steps.post_curation.pretext_to_asm_recurate import run_pretext_to_asm_recurate

    mock_ctx.workdir = tmp_path
    mock_ctx.tracker = None
    original_fa = tmp_path / "canonical.fa"
    original_fa.write_text(">seq\nACGT\n")
    mock_find_fa.return_value = original_fa
    (tmp_path / "recurate").mkdir()
    _agp(
        tmp_path / "recurate" / f"{mock_ctx.tol_id}.hap1.recurate.agp",
        [_ROW.format(name="Scaffold_4", component="SUPER_4_unloc_2_HAP1")],
    )

    with pytest.raises(click.ClickException) as exc:
        run_pretext_to_asm_recurate(mock_ctx, "hap1", "pretext_to_asm_recurate")

    assert "SUPER_4_unloc_2_HAP1" in str(exc.value)
    mock_run.assert_not_called()


_REAL_AGP = Path(__file__).parent / "fixtures" / "pretextviewai_2.0.0-beta_primary_tag.agp"


def test_parse_agp_tags_on_real_pretextviewai_agp():
    """Excerpt of a real PretextViewAI 2.0.0-beta AGP: tags sit in columns 10+, capitalised."""
    tags = parse_agp_tags(_REAL_AGP)
    assert tags["Scaffold_1"] == {"painted", "hap1", "primary"}
    assert tags["Scaffold_2"] == {"painted", "hap2"}
    # the gap rows of Scaffold_5 carry 9 fields and must not clear its tags
    assert {"painted", "falseduplicate"} <= tags["Scaffold_5"]


def test_primary_tag_check_accepts_real_pretextviewai_agp(mock_ctx_primary, tmp_path):
    mock_ctx_primary.combine_for_curation = True
    mock_ctx_primary.workdir = tmp_path
    mock_ctx_primary.tracker = None
    (tmp_path / "original.fa").write_text(">seq\nACGT\n")
    (tmp_path / f"{mock_ctx_primary.tol_id}.curated.agp").write_text(_REAL_AGP.read_text())
    with patch("grit.steps.post_curation.pretext_to_asm._run") as mock_run:
        _run_pretext_to_asm_core(
            mock_ctx_primary,
            "pretext_to_asm",
            tmp_path / "original.fa",
            "missing original.fa",
            tmp_path,
            f"{mock_ctx_primary.tol_id}.fa",
            _OUTPUT_SPECS,
        )
    mock_run.assert_called_once()


_REAL_UNLOC_AGP = Path(__file__).parent / "fixtures" / "pretextviewai_unloc_tag.agp"


def test_iter_agp_rows_on_real_recurate_agp():
    """Real recurate AGP: the carried-over unloc name is the component (col 6), not the object."""
    rows = iter_agp_rows(_REAL_UNLOC_AGP)
    unlocs = {component: tags for _name, component, tags in rows if "unloc" in component.lower()}
    assert set(unlocs) == {"SUPER_X_unloc_1_HAP1", "SUPER_X_unloc_2_HAP1"}
    assert all("unloc" in tags for tags in unlocs.values())
    # every row of that scaffold shares the same PretextView object name
    assert {name for name, _component, _tags in rows} == {"Scaffold_4", "Scaffold_5"}


def test_unloc_check_accepts_real_tagged_recurate_agp():
    _check_unloc_tags(_REAL_UNLOC_AGP)


def test_unloc_check_fails_on_real_agp_with_the_tag_dropped(tmp_path):
    stripped = tmp_path / "untagged.agp"
    stripped.write_text(
        "\n".join(
            "\t".join(f for f in line.split("\t") if f.strip().lower() != "unloc")
            for line in _REAL_UNLOC_AGP.read_text().splitlines()
        )
    )
    with pytest.raises(click.ClickException) as exc:
        _check_unloc_tags(stripped)
    assert "SUPER_X_unloc_1_HAP1" in str(exc.value)
    assert "SUPER_X_unloc_2_HAP1" in str(exc.value)


_REAL_UNLOC_OBJECT_AGP = Path(__file__).parent / "fixtures" / "pretextviewai_unloc_object_name.agp"


def test_unloc_check_accepts_recurate_agp_with_tagged_object_names():
    """A recurate map keeps the curated names, so the unloc name is the AGP object (col 1)."""
    _check_unloc_tags(_REAL_UNLOC_OBJECT_AGP)


def test_unloc_check_fails_on_untagged_object_names(tmp_path):
    stripped = tmp_path / "untagged_objects.agp"
    stripped.write_text(
        "\n".join(
            "\t".join(f for f in line.split("\t") if f.strip().lower() != "unloc")
            for line in _REAL_UNLOC_OBJECT_AGP.read_text().splitlines()
        )
    )
    with pytest.raises(click.ClickException) as exc:
        _check_unloc_tags(stripped)
    message = str(exc.value)
    assert "SUPER_X_unloc_1_HAP1" in message
    assert "SUPER_X_unloc_2_HAP1" in message
    assert "SUPER_X_HAP1" not in message.replace("SUPER_X_unloc_1_HAP1", "").replace(
        "SUPER_X_unloc_2_HAP1", ""
    )


def test_unloc_check_tag_on_any_row_of_a_multi_row_unloc_object(tmp_path):
    """An unloc object spanning several rows counts as tagged when any row carries the tag."""
    agp = _agp(
        tmp_path / "recurate.agp",
        [
            _ROW.format(name="SUPER_2_unloc_1_HAP1", component="HAP1_SCAFFOLD_9") + "\tPainted",
            _ROW.format(name="SUPER_2_unloc_1_HAP1", component="HAP1_SCAFFOLD_10")
            + "\tPainted\tUnloc",
        ],
    )
    _check_unloc_tags(agp)
